### PR TITLE
fix seq(iterator)

### PR DESCRIPTION
**Pull request by antimon2**
`seq(1:3)` didn't work, fix it.

### CODE REVIEW

**Comment by one-more-minute** [comment]
This looks like a good PR, thanks. I'm not sure about the API changes here, though. Reading `(x, y = z)` like a let binding is a nice idea but I'm worried that restructuring the syntax like that is going to be unintuitive. For example, `x, (y = z)` is going to be read the same as the above, right?

Maybe we could dial this back to just a simple fix for the `seq` issue, and discuss API changes in a separate PR?

Also, FYI, your test for `seq(1:3)` isn't sufficient to test for the problem (it works on Lazy.jl master already). You probably want to reify the list with some like `@test collect(seq(1:3)) == [1,2,3]`.

**Comment by antimon2** [comment]
In fact, as a normal assignment statement,  `x, y = (1, 2)` leads `x = 1` and `y = 2`.
But in `let` statement, `let x, y = (1, 2) …` leads `y = (1, 2)` and `x` is 'not defined'.
It has caused the problem, so I tried to rewrite `@with`.
(The behavior of `let` statement is rather unintuitive for me…)

I check again, and certainly `seq(1:3)` does NOT cause any Error.
For example, `Lazy.realize(seq(1:3))` causes an Error like that:
```
ERROR: x not defined
 in anonymous at /path/to/Lazy.jl/src/Lazy.jl:239
 in realise at /path/to/Lazy.jl/src/Lazy.jl:70
```

If you will stay `@with` definition (as same behavior as `let`), and fix `seq` definition, It's fine.
Then I drop my PR.

**Comment by antimon2** [comment]
remove multi-assignment of `@with`, and fix definition of `seq`.
(Leave Only-One Assignment feature of `@with` like `@with (x=1), 2x # => 2', which causes a Syntax Error on Lazy.jl v0.8.3)

How about this?
Or, Won't you fix the `seq(itr)` Error by yourself?

**Comment by antimon2** [comment]
I won't use `seq(1:3)`.
I've given up on it.

**Pull request closed without merging**
